### ISSUE TITLE
exception occured when the whole pixels are zero.

### ISSUE THREAD

**Issue by aflyingnoob** [jiwei0921/Saliency-Evaluation-Toolbox#1]
When the GT map is black, which means all of the pixels are 0, I got the error message:
``` matlab
index must be positive number

error WFb (line 33)
Et(~GT)=Et(IDXT(~GT)); %To deal correctly with the edges of the foreground region

error main (line 58)
    F_wm(i) = WFb(sal, logical(gt));
```

**Comment by aflyingnoob** [comment]
![GT](https://user-images.githubusercontent.com/30976978/97137671-547b5e00-1791-11eb-857a-43783593d0a5.png)
![map](https://user-images.githubusercontent.com/30976978/97137676-57764e80-1791-11eb-877d-0cb1e4f673cb.png)
you can try these two sapmles(the first is a GT map with pure black, the second is a salient map)

**Comment by aflyingnoob** [comment]
[test.zip](https://github.com/jiwei0921/Saliency-Evaluation-Toolbox/files/5437048/test.zip)
I have uploaded the test sample.

**Comment by jiwei0921** [comment]
Sorry, I don't understand you question in detail. Why GT is black?

**Comment by aflyingnoob** [comment]
The sample I get from a famous video salient dataset [DAVSOD](http://dpfan.net/davsod/), which contains pure black label (no salient object).
